version: '3'
services:
  web:
    build: 
    # Thay vi để dấu chấm thì sẽ không tìm được file dockerfile.dev
      context: . 
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    build: 
      context: . 
      dockerfile: dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]

