FROM node:16-alpine

USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# chown: 
COPY --chown=node:node package.json .
RUN npm install
COPY --chown=node:node . .

CMD ["npm","run","start"]